if (EXISTS "${PROJECT_SOURCE_DIR}/../pcre/")
  message (STATUS "Sibling PCRE found.")
  set (PCRE_FOUND TRUE)
  set (PCRE_INCLUDE_DIRS
    "${PROJECT_SOURCE_DIR}/../pcre/"
    "${PROJECT_BINARY_DIR}/../pcre/")
  set (PCRE_LIBRARY pcre)
  set (PCRE_LIBRARIES ${PCRE_LIBRARY})
  if (NOT PCRE_WITH_SHARED_LIBRARIES)
    add_definitions(-DPCRE_STATIC)
  endif ()
else ()
  message (STATUS "Sibling PCRE NOT found.")
endif ()

if (PCRE_FOUND)
  if (NOT TARGET Pcre::Pcre)
    if (NOT TARGET ${PCRE_LIBRARY})
      message (WARNING "Target ${PCRE_LIBRARY} is NOT FOUND. You should include PCRE as sibling library before ${PROJECT_NAME}.")
    else ()
      set_target_properties(${PCRE_LIBRARY} PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${PCRE_INCLUDE_DIRS}")
      add_library (Pcre::Pcre ALIAS ${PCRE_LIBRARY})
    endif ()
  endif ()
endif ()

if (PCRE_INCLUDE_DIRS AND NOT PCRE_INCLUDE_DIR)
  set (PCRE_INCLUDE_DIR ${PCRE_INCLUDE_DIRS})
endif ()
