if (EXISTS "${PROJECT_SOURCE_DIR}/../paho-mqtt-c/src/")
  message (STATUS "Sibling MQTT Paho found.")
  set (PAHO_FOUND TRUE)
  set (PAHO_INCLUDE_DIRS
    "${PROJECT_SOURCE_DIR}/../paho-mqtt-c/src/"
    "${PROJECT_BINARY_DIR}/../paho-mqtt-c/src/")
  if (PAHO_WITH_SHARED_LIBRARIES)
    if (PAHO_WITH_OPENSSL)
      message (STATUS "Using shared sibling MQTT Paho with OpenSSL.")
      set (PAHO_SYNC_LIBRARY paho-mqtt3cs)
      set (PAHO_ASYNC_LIBRARY paho-mqtt3as)
    else ()
      message (STATUS "Using shared sibling MQTT Paho.")
      set (PAHO_SYNC_LIBRARY paho-mqtt3c)
      set (PAHO_ASYNC_LIBRARY paho-mqtt3a)
    endif ()
  else ()
    if (PAHO_WITH_OPENSSL)
      message (STATUS "Using static sibling MQTT Paho with OpenSSL.")
      set (PAHO_SYNC_LIBRARY paho-mqtt3cs-static)
      set (PAHO_ASYNC_LIBRARY paho-mqtt3as-static)
    else ()
      message (STATUS "Using static sibling MQTT Paho.")
      set (PAHO_SYNC_LIBRARY paho-mqtt3c-static)
      set (PAHO_ASYNC_LIBRARY paho-mqtt3a-static)
    endif ()
  endif ()
  set (PAHO_LIBRARIES
    ${PAHO_SYNC_LIBRARY}
    ${PAHO_ASYNC_LIBRARY})
else ()
  message (STATUS "Sibling MQTT Paho NOT found.")
endif ()
