if (EXISTS "${PROJECT_SOURCE_DIR}/../jwt-cpp/include/")
  message (STATUS "Sibling jwt-cpp found.")
  set (JWTCPP_FOUND TRUE)
  set (JWTCPP_INCLUDE_DIRS
    "${PROJECT_SOURCE_DIR}/../jwt-cpp/include/")
  set (JWTCPP_LIBRARY jwt-cpp)
  set (JWTCPP_LIBRARIES ${JWTCPP_LIBRARY})
else ()
  message (STATUS "Sibling jwt-cpp NOT found.")
endif ()

if (JWTCPP_FOUND)
  if (NOT TARGET ${JWTCPP_LIBRARY})
    message (WARNING "Target ${JWTCPP_LIBRARY} is NOT FOUND. You should include jwt-cpp as sibling library before ${PROJECT_NAME}.")
  else ()
    if (NOT TARGET jwt-cpp::jwt-cpp)
      add_library (jwt-cpp::jwt-cpp ALIAS ${JWTCPP_LIBRARY})
    endif ()
  endif ()
endif ()

if (JWTCPP_INCLUDE_DIRS AND NOT JWTCPP_INCLUDE_DIR)
  set (JWTCPP_INCLUDE_DIR ${JWTCPP_INCLUDE_DIRS})
endif ()
